---

- name: Graylog | Checking config
  ansible.builtin.assert:
    that:
      - graylog is defined
  tags: always

- name: Graylog | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
