---

- name: Graylog-restart
  ansible.builtin.command: 'docker restart log-graylog'
  tags: skip_ansible_lint  # no-changed-when

- name: Graylog-rebuild
  ansible.builtin.systemd:
    name: 'graylog-update.service'
    state: started

- name: Opensearch-restart
  ansible.builtin.command: 'docker restart log-opensearch'
  tags: skip_ansible_lint  # no-changed-when
