---

- name: Graylog | Backup | Adding backup script
  ansible.builtin.template:
    src: 'templates/usr/local/sbin/graylog-backup.sh.j2'
    dest: '/usr/local/sbin/graylog-backup.sh'
    owner: 'root'
    group: 'root'
    mode: 0750

- name: Graylog | Backup | Adding backup service
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0755
  loop:
    - 'graylog-backup.service'
    - 'graylog-backup.timer'

- name: Graylog | Backup | Enabling/starting backup timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'graylog-backup.timer'
    enabled: true
    state: started
