---

- name: Graylog | Certs | Add PKI Bash-Alias
  ansible.builtin.blockinfile:
    content: |
      alias log-pki='docker run --rm -v {{ GL_HC.path.pki }}:/pki/pki -it local/pki /pki/pki.sh'
    path: '/root/.bashrc'
    marker: "# {mark} ANSIBLE MANAGED BLOCK LOG-PKI"

- name: Graylog | Certs | Check Server-Certificate
  ansible.builtin.stat:
    path: "{{ GL_HC.path.pki }}/issued/logserver.crt"
  register: gl_crt_file

- name: Graylog | Certs | Revoke existing Server-Certificate
  ansible.builtin.command: "docker run --rm -v {{ GL_HC.path.pki }}:/pki/pki -it local/pki \
  /pki/pki.sh revoke logserver"
  when:
    - gl_crt_file.stat.exists
    - regenerate_cert | bool
  tags: [skip_ansible_lint]  # changed when

- name: Graylog | Certs | Create Server-Certificate
  ansible.builtin.command: "docker run --rm -v {{ GL_HC.path.pki }}:/pki/pki -it local/pki \
  /pki/pki.sh --subject-alt-name='{{ cert_san }}' build-server-full logserver nopass"
  vars:
    cert_san: "{{ GL_CONFIG.pki.server_san |
    extend_list(GL_CONFIG.domain) | extend_list(GL_CONFIG.aliases) |
    build_cert_san }}"
  args:
    creates: "{{ GL_HC.path.pki }}/issued/logserver.crt"

- name: Graylog | Certs | Copy Server-Certificates
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    mode: 0640
    owner: 'root'
    group: 'graylog'
  with_items:
    - {s: "{{ GL_HC.path.pki }}/ca.crt", d: "{{ GL_HC.path.gl_ssl }}/ca.crt"}
    - {s: "{{ GL_HC.path.pki }}/issued/logserver.crt", d: "{{ GL_HC.path.gl_ssl }}/logserver.crt"}
    - {s: "{{ GL_HC.path.pki }}/private/logserver.nopw.key", d: "{{ GL_HC.path.gl_ssl }}/logserver.key"}
