---

- name: Graylog | Install | Docker
  ansible.builtin.include_role:
    name: ansibleguy.infra_docker_minimal
  vars:
    docker:
      compose:
        enable: true
      nftables:
        reload: "{{ GL_CONFIG.docker_nftables | bool }}"
        disable_iptables: "{{ GL_CONFIG.docker_nftables | bool }}"
  tags: docker
  args:
    apply:
      tags: docker

- name: Graylog | Install | Dependencies
  ansible.builtin.apt:
    name: ['zip', 'curl']

- name: Graylog | Install | Creating service users
  ansible.builtin.user:
    name: "{{ item.n }}"
    shell: '/usr/sbin/nologin'
    comment: 'Graylog Serviceuser'
    uid: "{{ item.u }}"
  loop:
    - {n: 'opensearch', u: "{{ GL_HC.uid.opensearch }}"}
    - {n: 'mongodb', u: "{{ GL_HC.uid.mongodb }}"}
    - {n: 'graylog', u: "{{ GL_HC.uid.graylog }}"}

- name: Graylog | Install | Creating Config-Dir
  ansible.builtin.file:
    path: "{{ GL_HC.path.config }}"
    state: directory
    mode: 0750
    owner: 'root'
    group: 'graylog'

- name: Graylog | Install | Creating Config-Dir 2
  ansible.builtin.file:
    path: "{{ GL_HC.path.config }}/server"
    state: directory
    mode: 0750
    owner: 'graylog'
    group: 'graylog'

- name: Graylog | Install | Creating OpenSearch Config-Dir
  ansible.builtin.file:
    path: "{{ GL_HC.path.config }}/opensearch"
    state: directory
    mode: 0750
    owner: 'root'
    group: 'opensearch'

- name: Graylog | Install | Creating OpenSearch Data-Dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: 'opensearch'
    group: 'opensearch'
  loop:
    - "{{ GL_HC.path.os_data }}"
    - "{{ GL_CONFIG.backup.path }}/opensearch"

- name: Graylog | Install | Creating MongoDB Data-Dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: 'mongodb'
    group: 'mongodb'
  loop:
    - "{{ GL_HC.path.mongo_data }}"
    - "{{ GL_CONFIG.backup.path }}/mongodb"

- name: Graylog | Install | Creating Graylog Data-Dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: 'graylog'
    group: 'graylog'
  loop:
    - "{{ GL_HC.path.gl_data }}"
    - "{{ GL_HC.path.gl_journal }}"
    - "{{ GL_CONFIG.backup.path }}/graylog"

- name: Graylog | Install | OpenSearch Dockerfile
  ansible.builtin.template:
    src: 'templates/etc/graylog/Dockerfile_opensearch.j2'
    dest: "{{ GL_HC.path.os_dockerfile }}"
    owner: 'root'
    group: 'docker'
    mode: 0640
  notify: graylog-rebuild

- name: Graylog | Install | MongoDB Dockerfile
  ansible.builtin.template:
    src: 'templates/etc/graylog/Dockerfile_mongodb.j2'
    dest: "{{ GL_HC.path.mongo_dockerfile }}"
    owner: 'root'
    group: 'docker'
    mode: 0640
  notify: graylog-rebuild

- name: Graylog | Install | Adding service files
  ansible.builtin.template:
    src: 'templates/etc/systemd/system/graylog.service.j2'
    dest: '/etc/systemd/system/graylog.service'
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Graylog | Backup | Adding update script
  ansible.builtin.template:
    src: 'templates/usr/local/sbin/graylog-update.sh.j2'
    dest: '/usr/local/sbin/graylog-update.sh'
    owner: 'root'
    group: 'root'
    mode: 0750
  tags: config

- name: Graylog | Install | Adding update service
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0755
  loop:
    - 'graylog-update.service'
    - 'graylog-update.timer'

# https://opensearch.org/docs/2.6/quickstart/
- name: Graylog | Install | Update systctl settings for Opensearch
  ansible.posix.sysctl:
    name: "{{ item.k }}"
    value: "{{ item.v }}"
    state: present
  loop:
    - {k: 'vm.swappiness', v: 1}
    - {k: 'vm.max_map_count', v: 262144}
