---

- name: Graylog | Install
  ansible.builtin.import_tasks: debian/install.yml
  tags: install

- name: Graylog | Config
  ansible.builtin.import_tasks: debian/config.yml
  tags: config

- name: Graylog | Backup
  ansible.builtin.import_tasks: debian/backup.yml
  when: GL_CONFIG.backup.enable | bool
  tags: backup

- name: Graylog | Webserver
  ansible.builtin.import_role:
    name: ansibleguy.infra_nginx
  when: GL_CONFIG.manage.webserver | bool
  tags: [webserver, install]
  vars:
    gl_nginx_config_overrides:
      domain: "{{ GL_CONFIG.domain }}"
      aliases: "{{ GL_CONFIG.aliases }}"
      proxy:
        proto: 'http'
        port: 9000
      security:
        restrict_methods: true
        allow_only_methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE']

    nginx:
      sites:
        graylog: "{{ GL_CONFIG.nginx | combine(gl_nginx_config_overrides, recursive=true) }}"

- name: Graylog | Enabling/starting service
  ansible.builtin.systemd:
    daemon_reload: yes
    name: 'graylog.service'
    enabled: yes
    state: started
  tags: install

- name: Graylog | Enabling/starting update timer
  ansible.builtin.systemd:
    daemon_reload: yes
    name: 'graylog-update.timer'
    enabled: yes
    state: started
  when: GL_CONFIG.auto_update.enable | bool
  tags: install
